framework:
    messenger:
        transports:
            order_queue: # Nom de la file d'attente
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        order_queue: ~
        routing:
            'App\Message\OrderMessage': order_queue