framework:
    messenger:
        transports:
            order_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        order_queue: ~
            panier_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        panier_queue: ~
        routing:
            'App\Message\OrderMessage': order_queue
            'App\Message\PanierGetOne': panier_queue
