framework:
    messenger:
        transports:
            PanierGetOne:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: PanierGetOne
                        type: direct
                    queues:
                        panier_get_one:
                            binding_keys: ['PanierGetOne']
        routing:
            'App\Message\PanierGetOne': PanierGetOne