framework:
    messenger:
        transports:
            panier_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        panier_queue: ~
            PanierGetOne:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        PanierGetOne:
                            binding_keys: [PanierGetOne]
                    queue_options:
                        durable: true
            routing:
            'App\Message\PanierGetOne': PanierGetOne


