framework:
    messenger:
        transports:
            panier_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            PanierGetOne:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: PanierGetOne
                        type: direct
                        default_publish_routing_key: PanierGetOne
        routing:
            'App\Message\PanierGetOne': PanierGetOne


