framework:
    messenger:
        transports:
            panier_queue:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            PanierGetOne:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order_exchange
                        type: direct
                    queues:
                        PanierGetOne:
                            binding_keys: [PanierGetOne]
                            arguments:
                                durable: false
        routing:
            'App\Message\PanierGetOne': PanierGetOne


