version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_breizsport_order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_breizhsport_order
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_symfony
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    networks:
      - symfony_network

  www:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: www_symfony
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/vhosts:/etc/apache2/sites-enabled
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  db-data:
